# Generated by Django 3.2 on 2022-11-01 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='words_per_player',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='players',
            field=models.ManyToManyField(blank=True, null=True, to='core.Player'),
        ),
    ]
