# Generated by Django 3.2 on 2022-11-01 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20221101_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamesession',
            name='players',
        ),
        migrations.AddField(
            model_name='player',
            name='game_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.gamesession'),
        ),
    ]
